baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'Craft Custom'
primary: true
siteGroup: 1ed41094-2678-4b13-97fb-2942a4d0b885 # Craft Samiullahmahjoor
sortOrder: 1
