dateModified: 1625581092
email:
  fromEmail: mahjoor_samiullah@hotmail.com
  fromName: 'Craft Samiullahmahjoor'
  transportType: craft\mail\transportadapters\Sendmail
plugins:
  embed-boards:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  labyrintoom-custom:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: 'Craft Samiullahmahjoor'
  schemaVersion: 3.6.8
  timeZone: America/Los_Angeles
