dateModified: 1625663631
email:
  fromEmail: craft@curatorwall.com
  fromName: 'Craft Samiullahmahjoor'
  replyToEmail: null
  template: ''
  transportSettings:
    encryptionMethod: ssl
    host: mail.curatorwall.com
    password: 'FE&?rDcc3-wJ'
    port: '465'
    timeout: '10'
    useAuthentication: '1'
    username: craft@curatorwall.com
  transportType: craft\mail\transportadapters\Smtp
plugins:
  embed-boards:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  labyrintoom-custom:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: 'Craft Samiullahmahjoor'
  schemaVersion: 3.6.8
  timeZone: America/Los_Angeles
